### ISSUE TITLE
"Resolve" an annotation

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/vision#109]
### Story

As a user using annotation for copy-editing, I can mark annotations that I've addressed as being resolved, so that I no longer have to see them and can keep track of what I have left to do.
### Acceptance criteria
- [ ] In the annotation controls, there is a resolve button.
- [ ] Clicking the resolve button reveals a text entry box allowing a rationale to be provided.
- [ ] An email is sent to the author advising them of the resolution and any rationale provided, and asking if they'd like to revert the resolution.
- [ ] Clicking a link to revert a resolution results in a web page saying that the resolution has been reverted.  No authentication is required.
- [ ] Annotations whose resolution has been reverted can be resolved again.
- [ ] A count is kept of resolutions that users make and how many are reverted for later use in metamoderation.

**Comment by klemay** [comment]
Closing in favor of: https://github.com/hypothesis/vision/issues/50
