### ISSUE TITLE
transcending the language barrier 3: support for manual translations

### ISSUE THREAD

**Issue by csillag** [hypothesis/vision#11]
#10 is about offering automatic translations of annotations.

This ticket is about offering the UI to do this manually.

This could work somehow like this:
- The user opens an annotation/highlight, which is (for example) in Spanish. (We should be storing this data, see https://github.com/hypothesis/h/issues/872 )
- He decides that he would like to add an English translation to this annotation, so he presses the button for it.
- A dialog box opens, when the user can enter his translation of the original text.
- When he clicks "save", a new annotation is created, which is targeting the original annotation, the has the meta-data describing that this is a translation, and who did it.
- Later, when a user views the original highlight/annotation, the system could detect that the language of the annotation is not within the set of the user's preferred languages, so it could search for existing translations for it, and automatically offer those, for example in a combo box. (It could offer multiple translations in the same language, if more than one users has translated it.)
- In the same combo box, we could also offer the original text, and also the automatic translation, as described in #10.

Of course, we should have a way to comment upon the translations themselves, too, but that's a more complex matter.

There could also be a settings panel for configuring this, so for example a user could configure that when there are translations from languages unknown to him, he should always see those translations immediately, when loading the annotation.

The same system could be used for the quotes, and also for the bodies of the annotation.

In a technical sense, this is similar to the generic "linking annotations together" feature (#4), but with a different UI.

**Comment by ajpeddakotla** [comment]
closing in favor of https://github.com/hypothesis/product-backlog/issues/905
