### ISSUE TITLE
If text is selected, adding a comment, should annotate the selection.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#114]
See: https://github.com/hypothesis/h/issues/1621

Acceptance Criteria:
- [ ] Provide a permanent way to create an annotation, separate from the adder.
- [ ] When text is selected, using the permanent control launches the editor with the selected text as the anchor.

**Comment by RawKStar77** [comment]
Closed via https://github.com/hypothesis/h/pull/2031

**Comment by tilgovi** [comment]
:cake:
