### ISSUE TITLE
Notify page authors of annotations

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/vision#120]
OGP.me, FoaF, Schema.org, and Dublin Core (etc, etc) all have ways to do this...

Simplest would probably be a [`rel="author"`](http://www.w3.org/TR/html5/links.html#link-type-author) on a `<link />` or `<a />` that points an email address or [author's URL](http://userinfo.me/) that can [receive notifications / messages](http://relify.com/). :smile_cat: 

Barring some sort of consistent discovery method, folks would have to know to care / check (like they do on Facebook, Twitter, etc)...but then we're back to another centralized thing to check inside of...and more profiles...and more accounts... :weary: 

:computer: :hammer:

**Comment by BigBlueHat** [comment]
Did some digging on this idea. Here's some options--the best one is last. ;)

### [FOAF OnlineAccount](http://xmlns.com/foaf/spec/#term_OnlineAccount)
This could work, but would require the author to generate some fairly complex metadata likely in the form of RDFa somewhere within the page. At the very least, it requires the splitting of the account URI into two values:
 - [accountName](http://xmlns.com/foaf/spec/#term_accountName) -- ex: `bigbluehat`
 - [accountServiceHomepage](http://xmlns.com/foaf/spec/#term_accountServiceHomepage) -- ex: 'hypothes.is'

Pro:
 - splits the account name into two bits which doesn't look like an email address, so it *may* decrease email-based spam at that user account address

Con:
 - splits the account name into two bits...
 - making the markup we'd suggest far less...legible...and a far more complicated setup

### [Open Graph Protocol](http://ogp.me/)
Slightly simpler. Could be reduced to a single `<meta />`, but it does imply that the page it's on is an `article` (or `book`)...which it may not be. Additionally, it's unclear what the value should be. [Facebook (unsurprisingly) wants URLs to Facebook Profiles](https://developers.facebook.com/docs/reference/opengraph/object-type/article). Other sites expect an author's full name... (some interesting chatter on the [Jetpack WordPress plugin discussion thread](https://wordpress.org/support/topic/questions-about-the-open-graph-meta-propertyarticleauthor-tag-in-jetpack-28)--which in theory could be used for publishing this metadata...if we went this route).

At best, we could attempt something like...
```html
<meta property="article:author" content="acct:bigbluehat@hypothes.is" />
```
which uses [RFC 7565](https://tools.ietf.org/html/rfc7565) `acct:` URI's (typically used with WebFinger).

Pros:
 - pretty commonly used pattern for stating authorship

Cons:
 - pretty commonly and *diversely* used pattern--so more implementation overhead
 - publishers may be adding incorrect metadata for their content--which could cause social sharing strangeness

### [HTML5 `author` Link Relation](http://www.w3.org/TR/html5/links.html#link-type-author)
Check it! It's been there this whole time!! HTML 1.1 actually used the `rev` attribute (which has been deprecated) of `made` to do this exact thing. :smile: 

So...it would look like this:
```html
<link href="acct:bigbluehat@hypothes.is" rel="author" />
```

It's clear ('cause these are ancient semantics) that the URI is for the author of the current resource (who's type is declared elsewhere--not in this metadata).

In the example above, I've used the `acct:` URI pattern again--'cause we use that internally, atm.

Pros:
 - proven to work
 - clear(er) authorship semantics
 - could use various URI or URL identification schemas--with less risk than `article:author` above

Cons:
 - various ways of identifying authors will need to be parsed (or ignored)
 - we'd need to pick one and stick with it--even if we change later

## Conclusion

I'm :+1: for the SimplestPossibleThingThatCouldPossiblyWork--which seems (to me) to be `rel="author"`.

Steps to use it would look like:
 - parse out `rel="author"`
 - narrow to `@hypothes.is` info (for now)
 - send notification to author via the hypothes.is notification system already in place

In future, we could consider parsing out `mailto` and `acct` and possibly handling profile docs (eventually) if someone uses an HTTP URL (of one shape [or another](http://userinfo.me/)).

But for now, we keep it simply, yeah?

**Comment by tilgovi** [comment]
Nice digging, @BigBlueHat.

I happen to like the `acct` scheme. I know it was a bit controversial. I remember having a conversion with Blaine Cook about how much he disliked it. In any case, [it's an RFC now](https://tools.ietf.org/html/rfc7565) and it makes our accounts seem very at home in an `href` attribute.

The biggest issue I see is that authors that may have little control over their markup.

Where we can give users a lot of control is with their user profiles. I imagine once we have profiles for users one could either link to their FB (without loss of generality) profile, possibly done implicitly through a delegated sign-in, and then we would recognize the  metadata when we see an author attribution that points to a user we know, even if it doesn't point to an Hypothesis account directly.

As for simplest thing that could possibly work, using `rel=author` for publishers that can control the markup and pointing directly to Hypothesis accounts seems totally tenable.

**Comment by BigBlueHat** [comment]
So...it's a sad truth that too few WYSIWYG editors (and their ilk) don't provide `rel="author"` editing. That said, the `rel="author"` attribute can exist on `a` as well as `link`, so putting into the content of the page (vs. "just" in the `<head>`) is an option also.

We could certainly sniff out and leverage other values of `rel="author"` besides the `acct:(.*)@hypothes.is" pattern. We could certainly leverage Facebook URLs (+ a stored association on our end), but even sooner than that, we could leverage a `mailto:` to then look up a hypothes.is account. However, since you can have N number of hypothes.is accounts for per email address, picking the right one might be tricky...but since the notification comes over email, perhaps it's not a problem.

So...in preferred ordering, we could look up the author's account using:
1. the `acct` prefixed value (if present)
2. or `http` prefixed value (assuming "social" URL such as Facebook, etc)
3. or `mailto` prefixed value looking for any verified account using that email address

Then we notify the author based on them having (based on that look-up strategy) a verified hypothes.is account.

Sound safe?

This way authors wouldn't need to displace any extent `rel="author"` values that === a URI or URL. Or so it seems. :wink:

**Comment by tilgovi** [comment]
This is all a bit tricky and needs to be thought through carefully with consideration paid to spam vectors, markup in the wild today, our identity strategy, etc, etc.

Maybe we can punt on this and start with an explicit watch toggle in the UI. That enables notification for authors and non-authors, both requested features. It wouldn't be automatic, but it would step around all these issues for the time being.

**Comment by dwhly** [comment]
> Maybe we can punt on this and start with an explicit watch toggle in the UI. That enables notification for authors and non-authors, both requested features.

Heartily endorse this as an initial step.  It's something that we need regardless.

I think the markup idea is great too, particularly as a feature of an H. wordpress plugin that could automatically add it, and make notifications automatic for pages.  For instance, with our own site, it would be great if I author an article, I'm automatically notified of annotations.  But perhaps as a follow-on feature?

**Comment by tilgovi** [comment]
> But perhaps as a follow-on feature?

Precisely what I'm suggesting.

**Comment by jeremydean** [comment]
You had me at "explicit Watch toggle in the UI"

On Tuesday, June 16, 2015, Randall Leeds <notifications@github.com> wrote:

> But perhaps as a follow-on feature?
>
> Precisely what I'm suggesting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hypothesis/vision/issues/120#issuecomment-112619485>.
>


-- 
Dr. Jeremy Dean
Director of Education

**Comment by dwhly** [comment]
> You had me at "explicit Watch toggle in the UI"

You had me... meaning "what the heck are you talking about?" :)

A watch toggle would mean that anyone could signal they wanted to watch any page, whether there were annotations on it or not.  Then we can begin to layer additional notifications on.

**Comment by jeremydean** [comment]
Yes. I know. I love the idea of that feature is what I meant. It's a
reference jerry McGuire.

On Tuesday, June 16, 2015, Dan Whaley <notifications@github.com> wrote:

> You had me at "explicit Watch toggle in the UI"
>
> You had me... meaning "what the heck are you talking about?" :)
>
> A watch toggle would mean that anyone could signal they wanted to watch
> any page, whether there were annotations on it or not. Then we can begin to
> layer additional notifications on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hypothesis/vision/issues/120#issuecomment-112629753>.
>


-- 
Dr. Jeremy Dean
Director of Education

**Comment by dwhly** [comment]
My cultural references ended somewhere around All In the Family.

**Comment by hubgit** [comment]
Allowing a user with a hypothes.is account to manually opt-in to receiving notifications when a particular URL is annotated seems like a good idea.

At another level, might it be possible for a service to register an endpoint as a listener for any annotations of documents in a particular domain (e.g. "when a URL with domain `peerj.com` is annotated, send that annotation to webhook endpoint `https://peerj.com/hooks/annotations`"). Then the service, which knows who the authors of that document are, could handle notifying them by email.

**Comment by tilgovi** [comment]
WebHooks are a great idea, as well, and would be great for integrations. User subscription is great for individual users.

Both can be made better through discovery.

Let's try to keep all these steps separate as we create concrete issues for implementation.

**Comment by BigBlueHat** [comment]
Some stories:

- As a Hypothes.is account holder, I want to watch / follow pages I visit and be notified of annotations made on them, so that I can (re)join the conversation if someone annotates there.
  - this is any URL
  - no "authorship" implied
  - all users have the same opportunity

- As a web site owner, I want Hypothes.is to tell me when my pages are annotated, so that I don't have to follow ever URL I post or get notified on everything at a certain URL or under a certain URL space.
  - example: author installs the Hypothes.is WordPress extension which adds some metadata to the site for `embed.js` to extract

- As an author of content in a system I don't control (read: most of the Web), I want to watch for annotations on a domain, URL "space" (i.e. twiter.com/bigbluehat/*), or specific URLs, so that I can engage my readers without requiring permission / technology changes from my publisher.
  - most users don't own / host their code

- As an author of content using a CMS that supports a notification system (pingback, trackback, webmention), I want that system to be used (as it is already) when someone posts content related to my original post, so that I can know about the conversation and join it at my discretion.

These are four stories that all seem to have some appearance in this thread. I'm trying to winnow them into actionable separate tasks that can be tackled...separately. None of these options cover all the desires authors (or annotators) have around being notified; nor should they.

I'd love another set of eyes on those four stories, and addition of any stories that clearly explain another variation (I expect there probably are more). The follow-up action will be to create (or find) separate issues for each of these and tackle them one at a time. :elephant: :fork_and_knife:

**Comment by jeremydean** [comment]
Does this user story add anything to the mix? (Or bring up a completely
different issue: following users/sets of users rather than URLs?):


   - As an "administrator" (teacher, group organizer) of a group, I want to
   be able to watch/follow URLs annotated by the group and receive
   notifications of group activity--maybe even beyond designated URLS, that is
   following the user/member annotations wherever they are online.


Aside from that added use for following/notifications, I would just say
that your first bullet point is the most critical and should be a
priority--seems a lot of the latter bullets could be accomplished if we had
a page follow feature--just asking a little more of users. Though I love
the ideas for the other issues!
ᐧ

On Wed, Jul 1, 2015 at 10:26 AM, BigBlueHat <notifications@github.com>
wrote:

> Some stories:
>
>    -
>
>    As a Hypothes.is account holder, I want to watch / follow pages I
>    visit and be notified of annotations made on them, so that I can (re)join
>    the conversation if someone annotates there.
>     - this is any URL
>       - no "authorship" implied
>       - all users have the same opportunity
>     -
>
>    As a web site owner, I want Hypothes.is to tell me when my pages are
>    annotated, so that I don't have to follow ever URL I post or get notified
>    on everything at a certain URL or under a certain URL space.
>     - example: author installs the Hypothes.is WordPress extension which
>       adds some metadata to the site for embed.js to extract
>     -
>
>    As an author of content in a system I don't control (read: most of the
>    Web), I want to watch for annotations on a domain, URL "space" (i.e.
>    twiter.com/bigbluehat/*), or specific URLs, so that I can engage my
>    readers without requiring permission / technology changes from my publisher.
>     - most users don't own / host their code
>     -
>
>    As an author of content using a CMS that supports a notification
>    system (pingback, trackback, webmention), I want that system to be used (as
>    it is already) when someone posts content related to my original post, so
>    that I can know about the conversation and join it at my discretion.
>
> These are four stories that all seem to have some appearance in this
> thread. I'm trying to winnow them into actionable separate tasks that can
> be tackled...separately. None of these options cover all the desires
> authors (or annotators) have around being notified; nor should they.
>
> I'd love another set of eyes on those four stories, and addition of any
> stories that clearly explain another variation (I expect there probably are
> more). The follow-up action will be to create (or find) separate issues for
> each of these and tackle them one at a time. [image: :elephant:] [image:
> :fork_and_knife:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hypothesis/vision/issues/120#issuecomment-117693473>.
>



-- 
Dr. Jeremy Dean
Director of Education

**Comment by tilgovi** [comment]
I think I'm seeing this breakdown:

- Follow Hypothesis activity with Hypothesis
  - User page watches
    - This is @BigBlueHat's first case
  - User search watches
    - This is the "site owner" and "administrator" case
- Follow Hypothesis activity with <federated protocol>
  - Pingback, trackback, webmention
  - This also covers site owners who can support these protocols, like CMS administrators

**Comment by tilgovi** [comment]
Single page watches should be relatively easy with a decent notification system in place. @judell and @BigBlueHat we should work to get a first task of reviewing our current notification system and banging it into some greater generality, cleanliness and testability. Then, users could watch pages. We'll deal with search later, because we should write a percolation (prospective search) worker and use it for pushing real-time updates, too. Same issue (persistent search), different notification mechanisms (WebSocket and Email), though not mutually exclusive when background notifications are surfaced in the UI as well as email.

Prerequisite:
- Notification system prep and house cleaning

First feature:
- Single page email notifications

In Parallel, and with the work @nickstenning has been proposing around fixing our URI analysis:
- Pingback, trackback, webmention sent from our API

Next generation:
- Persistent search
- Unified notifications for clients and email

**Comment by BigBlueHat** [comment]
:+1: for that plan.

**Comment by judell** [comment]
Good, thanks. I've added this context and the first few steps to our tracking card in Up Next.

**Comment by pyrho** [comment]
I've checked the [trello](https://trello.com/b/2ajZ2dWe/public-roadmap) page but I can't find any mentions regarding progress on this, are there any updates ?

I realise RSS has been implemented, but I'm talking specifically about this (mentioned above):

> * As a web site owner, I want Hypothes.is to tell me when my pages are annotated, so that I don't have to follow ever URL I post or get notified on everything at a certain URL or under a certain URL space.
> example: author installs the Hypothes.is WordPress extension which adds some metadata to the site for embed.js to extract

I love the web annotation approach to web site comments, but I'd also love to be notified of new comments on my website without having to subscribe to N rss feeds (N being the number of posts).

Thanks you !

**Comment by klemay** [comment]
See also: https://github.com/hypothesis/product-backlog/issues/212
