### ISSUE TITLE
Metrics: Extension installs

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#122]
We should track the number of installs we have for each extension we ship.  Nick suggested that because of the source of the data was distinct, it should have its own card.

Acceptance criteria:
- [ ] Daily reporting of current active Chrome extensions (extensions which have phoned home in last 7 days)
- [ ] Daily reporting of total active FF extensions (extensions which have phoned home in last 7 days)

**Comment by tilgovi** [comment]
See #151
