### ISSUE TITLE
Rework Annotator Markdown plugin

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/vision#125]
The Annotator Markdown plugin is still written in CoffeeScript. The relevant functionality and tests should be translated into JavaScript and probably moved to an appropriate place in the `Annotator.UI` package.

If you pick up this story, please come and discuss possible design approaches with me.

**Comment by gergely-ujvari** [comment]
Implemented in PR: https://github.com/openannotation/annotator/pull/474
