### ISSUE TITLE
Rework Annotator Auth plugin

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/vision#126]
The Annotator Auth plugin is currently defunct. There needs to be a way for an Annotator instance to know that it must retrieve an auth token before performing storage calls. I suggest this moves into an option to the storage plugin, or some component which knows how to reconfigure the storage plugin appropriately.

If you pick up this story, please come and discuss possible design approaches with me.

**Comment by tilgovi** [comment]
Our auth service and store service now interact completely differently, by using $http and interceptors.
