### ISSUE TITLE
Convert Annotator inline documentation to JSDoc

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/vision#127]
Convert the inline (method and package) documentation into JSDoc, so that we can publish decent generated API documentation.

We don't need to go overboard with our use of JSDoc annotations, but some structure and cross-referencing would be very helpful.

**Comment by dwhly** [comment]
Are we now agreeing this shouldn't be in vision?

**Comment by tilgovi** [comment]
Yeah. I'll move this to annotator.

**Comment by tilgovi** [comment]
Moved to openannotation/annotator#486
