### ISSUE TITLE
Show annotation count when extension is off (Listening mode)

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#132]
As a user, I want to know whether there are annotations on a page even if the sidebar is not deployed.  

We used to refer to this as "listening mode" and it was discussed as part of the original feature set of the extension, here: https://github.com/hypothesis/h/issues/43#issuecomment-12944052

Also our wiki page discusses some possible listening states-- which we can obviously revisit-- here: https://github.com/hypothesis/h/wiki/Browser-extension

Issues include: 
- Privacy implications of leaking sites visited to the server even when the extension is "off" and whether that should be configurable. 
- Whether to try to show a number or "99+" annotations when there are many.
- The number of states the extension toggle should have (keep it simple).

This has been the subject of multiple requests in user testing feedback, including most recently here [archive still updating]:
http://list.hypothes.is/archive/dev/2014-11/0000056.html

**Comment by robertknight** [comment]
The first version of this has now been implemented as a count displayed on the extension badge.
