### ISSUE TITLE
Sign in after claiming account

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/vision#133]
As someone choosing a password for my reserved username, I'd like to be logged in once I have successfully activated, so that I can immediately start using the software.

### Acceptance criteria

- [ ] When a user who has reserved their username clicks on an email claim link, they are sent to a page where they can choose a password.
- [ ] When they have chosen a password, their account is immediately activated and they are signed in.

**Comment by tilgovi** [comment]
With hypothesis/h#1941 this is done.
Thanks @nickstenning and @aron.
