### ISSUE TITLE
Narratives / Threads / Trails

### ISSUE THREAD

**Issue by csillag** [hypothesis/vision#14]
I am migrating this from https://github.com/hypothesis/h/issues/385

```
* * *
```

It would be nice to have a way to build a sequence of annotations, and show them together. Would be especially useful with highlights.

The goal is to have a way to present a sequence of thoughts, quotes, whatever, that together tell a story, or illustrate a train of thought, or something like that.

Could also be used for presenting a reading list, or a manually created news feed.

This is somewhat similar to the stream with configured filters, but not the same, because the sequence of annotations is not generated on request, but stored in the DB, and we actually have to have a UI for building it.

For showing a narrative: we could have linkable narrative pages very similar to linkable annotations, with the following differences:
- multiple annotations are shown, in the pre-determined order, not only one
- replies are optional (user should be able to toggle them on and off)
- maybe there could be really short text sections for connecting the annotations. (Showing text that is stored as part of the narrative.)

For building a narrative: we need a UI that supports drag-and-drop building and reordering. (We should probably show only a shortened form of the annotation, not the full text of body/quote).  We also need some feature to edit the text segments connecting the annotations (if any).

Also, we should also provide an API endpoint to retrieve the annotations belonging to a narrative in a raw, JSON form (like we do with single annotations), so that users who want to build their custom display UI can do that, too.

(I think Ian has mentioned that they might want to show the threads embedded in their pages.)

**Comment by ajpeddakotla** [comment]
closing in favor of https://github.com/hypothesis/h/issues/385
