### ISSUE TITLE
Print/export document with annotations on margin

### ISSUE THREAD

**Issue by csillag** [hypothesis/vision#143]
As a user, I expect to be able to print a document I have annotated, with the annotations appearing on the margin.
- [ ] All annotations should be visible, and the layout optimal (whatever is possible given the density of annotations)
- [ ] The annotations should be linked to the highlights. (Either numbering them the classical way, or drawing some kind of markers for them could work)
- [ ] The interactive features (like controls and buttons) should all be hidden

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/21
