### ISSUE TITLE
Integrate via.hypothes.is with the homepage.

### ISSUE THREAD

**Issue by RawKStar77** [hypothesis/vision#149]
As a user, I would like to be able to quickly generate a link that embeds hypothes.is on a URL.

--- 

The bookmarklet experience is not a good one. There are problems with not working on HTTPS pages as well as usability problems, especially the confusion that results when people wonder how to install the bookmarklet and they don't have the bookmarks toolbar visible in their browsers. For collaborative annotation, it is annoying to wait for everyone to get the bookmarklet or annotation installed. All of this can be greatly improved.

via.hypothes.is provides a way we can create links that embeds h on a page. We should incorporate this into our homepage with a simple form. Something along the lines of *Paste in a link* next to a button that says perhaps *Annotate*. This would return a link that could be copied and shared.

**Comment by tilgovi** [comment]
\o/
