### ISSUE TITLE
Annotation, Highlight, and Comment Creation: UX Refactor

### ISSUE THREAD

**Issue by RawKStar77** [hypothesis/vision#152]
As a user, I want an easy and mobile friendly workflow for creating annotations, highlights, and general comments.  

I've already started a design dock with some drawings around how we can improve UX in this area (feel free to annotate with Hypothes.is):
https://docs.google.com/document/d/1Qq6aDo45DoIpYDPrrSDnyL_GGWjcos3tWDBFgxBqeEs/pub

Relevant GitHub issues that are currently open:
https://github.com/hypothesis/h/issues/1386
https://github.com/hypothesis/h/issues/1261
https://github.com/hypothesis/h/issues/587

**Comment by BigBlueHat** [comment]
hypothesis/h#1984

**Comment by RawKStar77** [comment]
Closed via https://github.com/hypothesis/h/pull/2031
