### ISSUE TITLE
Hide orphan annotations

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/vision#153]
Sometimes annotations don't reanchor on a page. We call these "orphan" annotations. At the moment we display them. This is confusing. (q.v. older issue #1769)

In future, we may do smarter things with orphan annotations. For now, don't render them.

### Acceptance criteria

- [ ] When I visit a page that has changed significantly, I don't see orphan annotations in the sidebar.

**Comment by csillag** [comment]
Implementation being tracked in https://github.com/hypothesis/h/issues/1612

**Comment by tilgovi** [comment]
Merged in hypothesis/h#2080
