### ISSUE TITLE
Load all annotations

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/vision#154]
When we load a page, we should be loading all annotations pertaining to that page, possibly over multiple requests, so that users aren't confused by disappearing annotations, partial loads, or empty pages (if the subset loaded are all orphans, for example).

**Comment by csillag** [comment]
Aren't we doing that?

(Or do you mean the 1000 annotation limit?)
2015.02.09. 19:46 ezt írta ("Nick Stenning" <notifications@github.com>):

**Comment by csillag** [comment]
Oh, I see. There is a limit, and it's too low.
