### ISSUE TITLE
With via on PDFs, clicking on an annotation doesn't scroll the document.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#158]
For instance, here:
https://via.hypothes.is/static/ann/viewer/web/viewer.html?file=/h/id_/http://project.hypothes.is/design/page_vs_interpage_groups/page_vs_interpage_groups.pdf

Open the sidebar, select an annotation.  Click on it.

**Comment by BigBlueHat** [comment]
Yeah...definitely some weirdness here, but I don't think it's Via related--but it could be related to how we work with the version of PDF.js Via is shipping: 1.0.473

I'm going to close this here, though in favor of opening another one on h (as it's not a terribly visionary sort of bug). :smiley:

**Comment by BigBlueHat** [comment]
Ah. As I'd guessed, @csillag reported this sometime ago as https://github.com/hypothesis/h/issues/1873

**Comment by csillag** [comment]
> Ah. As I'd guessed, @csillag reported this sometime ago as
hypothesis/h#1873

I didn't only report it; I have also fixed it. My PR is still pending,
waiting to sort out all the tests...

**Comment by BigBlueHat** [comment]
:gift:
