### ISSUE TITLE
Sort order isn't by location

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#159]
Go here:
https://via.hypothes.is/static/ann/viewer/web/viewer.html?file=/h/id_/http://project.hypothes.is/design/page_vs_interpage_groups/page_vs_interpage_groups.pdf

Open the sidebar.  Order is not by location.

**Comment by csillag** [comment]
Is this not the same as https://github.com/hypothesis/h/issues/1647 ?

**Comment by csillag** [comment]
Is this specific to via, or does this also happen when viewing natively?

Isn't this a duplicate of https://github.com/hypothesis/h/issues/1647 ?

**Comment by BigBlueHat** [comment]
Yeah. Agreed with @csillag. Closing in favor of hypothesis/h#1647

**Comment by dwhly** [comment]
Sorry, thanks guys.
