### ISSUE TITLE
Cannot close share-popup

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#163]
Tracking https://github.com/hypothesis/h/issues/1802

**Comment by tilgovi** [comment]
@dwhy could you use some language other than "duplicate" when you do this? I'm so used to seeing that as a reason to close something in bug trackers. Maybe "tracking"?

**Comment by dwhly** [comment]
Yup changed.

**Comment by nickstenning** [comment]
Closed by hypothesis/h@67080d6f5c46943f47390096ee39d56cc87d2c96.
