### ISSUE TITLE
Get Firefox extension operational

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#165]

**Comment by BigBlueHat** [comment]
Duplicates (intentionally): https://github.com/hypothesis/h/issues/1956

Fixing it requires going through [these steps](https://github.com/hypothesis/h/issues/1954#issuecomment-74970756) and improving the build process accordingly.

**Comment by tilgovi** [comment]
@BigBlueHat I had asked @dwhly to say something other than "duplicate". I suggested "tracking" but also "references" or "ref" works. Any notation you want.

The point is that it doesn't really duplicate. We may split / change / open / close issues on h independently of a particular feature making it through our product backlog.

**Comment by BigBlueHat** [comment]
Updated my comment accordingly. Tnx @tilgovi

**Comment by dwhly** [comment]
Does this mean we're ready to update the add-on store? https://addons.mozilla.org/en-US/firefox/addon/hypothesis/

**Comment by tilgovi** [comment]
Probably.
