### ISSUE TITLE
Send out activation email for people who reserved usernames

### ISSUE THREAD

**Issue by JakeHartnell** [hypothesis/vision#172]
### Acceptance Criteria:
- [x] Finish email text
- [x] Generate test claim links and emails
- [x] Ensure product release with all features and bugfixes necessary is live and tested
- [x] Continue emailing blocks of users until complete

**Comment by RawKStar77** [comment]
It would be really nice if someone could start working on creating the dummy usernames and generating test claim links and emails... this and #171 are at the top of the backlog for a reason. : )

Is this issue clear enough on what needs to get done?

**Comment by nickstenning** [comment]
We've agreed that this is blocked by hypothesis/h#2026, hypothesis/h#1916, and hypothesis/h#2076.

**Comment by tilgovi** [comment]
Done.

**Comment by JakeHartnell** [comment]
:fireworks:
