### ISSUE TITLE
Add an Atom feed for the /stream page

### ISSUE THREAD

**Issue by seanh** [hypothesis/vision#179]

**Comment by seanh** [comment]
This is done and merged but I'm leaving it open because not deployed to production yet

**Comment by judell** [comment]
https://github.com/hypothesis/vision/issues/170 says: "Current filters in place on the /stream would be able to be subscribed to, as long as the results are public to all." Is that the case?

I'm trying to relate https://github.com/hypothesis/h/blob/6f13674f17493a70d1c2b087db97a0747cb8c7ea/h/views.py#L113 to what comes in on the URL-line for non-Atom and Atom /stream requests, 

I don't care what the syntax is, only that these patterns:

https://hypothes.is/stream?q=tag:TAG
https://hypothes.is/stream?q=uri:URI
https://hypothes.is/stream?q=user:USER

have corresponding Atom equivalents.

Do they? And if so, what are those patterns?

If all will exist and this is almost done I'll move the Atom Feeds card in the sprint from Backlog to Commitments and perhaps soon to Done.

**Comment by seanh** [comment]
What's been merged into master right now just creates a feed of exactly what you see at /stream (if you don't do any filtering or sorting or anything). So it's all public annotations, and anyone can subscribe to this feed.

> https://hypothes.is/stream?q=tag:TAG
> https://hypothes.is/stream?q=uri:URI
> https://hypothes.is/stream?q=user:USER
> 
> have corresponding Atom equivalents.

Nope :( The stream is equivalent to `https://hypothes.is/stream` only. But those patterns could be added very easily The current stream is `/stream.atom` so I would suggest `https://hypothes.is/stream.atom?q=tag:TAG` etc.

**Comment by seanh** [comment]
http://stage.hypothes.is/stream.atom

**Comment by judell** [comment]
OK, then I will propose not to ship this without those patterns, every important use case involves one or another of them. 

And we're back to what I originally thought, and why I left Atom Feeds in the Trello backlog: this is easy, but not a priority for this cycle. If everything else gets done and you're looking for a task, then by all means come back to this.

**Comment by seanh** [comment]
This is already in master, if we want to not ship it we'll have to add a feature flag for it. Or we could just ship it but not mention it? The feed is discoverable though.

**Comment by tilgovi** [comment]
I don't see any reason _not_ to ship it. It may not be the most useful thing yet but it isn't broken and it's not distracting for users.

**Comment by tilgovi** [comment]
Actually, if I had one suggestion I'd say we should just move the URL so that it's less likely to imply a relationship between /stream (which takes a query string) and the atom feed (which doesn't yet).

I think the right way forward here involves someone doing a comprehensive dive into hypothesis/h#1471 and start thinking about the merits of different URL structures.

Straw persons:

- /collection/all{.atom}
- /search (may or may not have atom feed)
- /collection/by_tag/{tag}{.atom}
- /collection/aX7OuRTnthoe     <--- maybe some protected / private group

etc

**Comment by tilgovi** [comment]
So to wrap up my thoughts, if anyone thinks it's problematic to have /stream.atom given that it doesn't have support for query strings and maybe should be moved eventually, we should put it behind a feature flag and disable it, but at this stage I'm not that worried about this. Developers aren't normal users, they understand that these interfaces are subject to rapid change when a project is young and our version number is, after all, still 0.3.x.

**Comment by judell** [comment]
If it's already in the chute then OK, no harm. From a sprint planning
perspective I'll leave the more complete feature in backlog for later.
Thanks.

**Comment by BigBlueHat** [comment]
@seanh we good to close this now?
