### ISSUE TITLE
Enable inline videos

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#185]
In annotation bodies.  Request from @jgmac1106.

**Comment by jgmac1106** [comment]
Thanks. It may seem like a small use case but K12 teachers use this feature a lot. Linking to YouTube is okay but being able to. Have video embedded would be nice. Using Google Drive videos, even better.

**Comment by csillag** [comment]
Ideally, we should be support oEmbed content, which covers this.
See the description and example at WordPress's documentation:

https://codex.wordpress.org/Embeds

We could you the same user-facing syntax and standards.

**Comment by dwhly** [comment]
> It may seem like a small use case

It doesn't at all.  Thanks for the additional detail.

cc @jeremydean

**Comment by robertknight** [comment]
Support for inline videos from YouTube  and Vimeo has been implemented. Others will come in future.
