### ISSUE TITLE
A github.io page doesn't work on Safari

### ISSUE THREAD

**Issue by ctb** [hypothesis/vision#197]
https://via.hypothes.is/swcarpentry.github.io/good-enough-practices-in-scientific-computing/

**Comment by robertknight** [comment]
Thanks for the report @ctb . Unfortunately Via is not working at all on Safari at the moment, I'm currently fixing this. I'd suggest subscribing to the existing issue at https://github.com/hypothesis/via/issues/59

**Comment by ctb** [comment]
thank you!
