### ISSUE TITLE
[feature request] Public groups

### ISSUE THREAD

**Issue by damaru2** [hypothesis/vision#230]
I sometimes want to write a note and share it to other people, but it is not something really relevant to the public (it could be just rubbish to them, for instance write down the relation of an academic paper with another one in an specific setting that only me and a couple of colleagues understand) but the other people don't have hypothesis. If the note is public I can share it with them despite they don't have hypothesis but then I'd be adding irrelevant notes to other people in that website.

So what if instead there were public groups. Everybody could join a public group with a link and see the notes but besides of this, you can share a note to somebody that it is not in the group and they can see it, in the same way as a note that was shared as _public_.

**Comment by ajpeddakotla** [comment]
@damaru2 excellent feature request, and this is something that we're indeed working on right now. Thanks again for your feature request, and we'll announce on our blog once we've launched it.
