### ISSUE TITLE
[Feature request] Move notes from one group to another.

### ISSUE THREAD

**Issue by damaru2** [hypothesis/vision#233]
Say you have written a note in a group A instead of in a group B. You want to make the note belong to group B but the only way there is now to do this is to copy the note, create a new note in group B by selecting exactly the same text and pasting the note. Then the note in group A would have to be deleted. All this could be done straightforwardly with a feature to move the note from one group to another

**Comment by klemay** [comment]
Hi @damaru2! We agree that this would be a useful feature addition. We have an open item for this in our product backlog, so I'm going to close this issue in favor of that one. You can follow progress on this feature request here: https://github.com/hypothesis/product-backlog/issues/111
