### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#24]

**Comment by dwhly** [comment]
I'm fairly positive I tested via.hypothes.is with IE11 last week.  However, at present, I cannot get the adder to show.  This would be great to fix before we send emails next week.  Bumping this higher. 

@gergely-ujvari did you notice an adder issue previously or is that a regression?

**Comment by gergely-ujvari** [comment]
No, I haven't seen this error in the past.

**Comment by gergely-ujvari** [comment]
Oh wait.. I have! It means that the d-t-m library is probably throwing an exception.

**Comment by csillag** [comment]
We are not using the d-t-m with IE.
We are supposed to deploy on IE with a specific request parameter, 
turning off d-t-m.

(I proposed to make that automatic, but the decision was to make this 
the responsibility of the integrator, so currently it needs to be done 
manually.)

2015. márc. 11., sze 23.12-kor-kor, gergely-ujvari 
<notifications@github.com> írta:

**Comment by tilgovi** [comment]
I can't remember if the last time we discussed this was before the `hypothesisConfig` embed hooks. I think I may be okay with having a default hook try to feature detect for IE.

**Comment by csillag** [comment]
> I may be okay with having a default hook try to feature detect for IE.

Great! See PR https://github.com/hypothesis/h/pull/2047

**Comment by csillag** [comment]
However, we have another, non d-t-m related bug; see https://github.com/hypothesis/h/issues/2048

**Comment by judell** [comment]
In both https://ie.dokku.hypothes.is/ (if that's relevant) and the current live product, IE 11 does not display annotations.
