### ISSUE TITLE
Annotate local documents (one's without URLs)

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/vision#47]
[RFC 6920](http://tools.ietf.org/html/rfc6920) at the IETF is a system for creating content-based hash values (using various hashing algorithms) and expressing those as URIs.

If we (or the browser) could/would generate these `ni://` URIs for content on and off (loaded via `file:///`) the Web, we could reliably relate the annotations made to a local PDF (like my copy of "Information Management: a proposal") to it's online counterpart (if/when it exists and is found by the annotator's user agent).

**Comment by pguth** [comment]
I would argue for using a [IPFS](https://ipfs.io/) compliant way of hashing the files. There is an ongoing discussion regarding the naming scheme [here](https://github.com/ipfs/go-ipfs/issues/1678).

A user facing place for us to integrate this would be in the [stream view](https://hypothes.is/stream?q=user:pguth). There is already a gateway to access content via the web (eg. [here](https://ipfs.io/ipfs/QmTeW79w7QQ6Npa3b1d5tANreCDxF2iDaAPsDvW6KtLmfB/): there you see an old version of their site). Maybe @jbenet could be our point of contact.

In my opinion is IPFS the most likely candidate for solving the content addressing problem and they do nice work integrating the whole thing within the web platform.

**Comment by akuckartz** [comment]
How was this resolved?

**Comment by ajpeddakotla** [comment]
@akuckartz you can annotate a local copy of a pdf today. We've even written up instructions on how to do this here: https://web.hypothes.is/help/annotating-locally-saved-pdfs/

Annotating other offline documents such as .docx or other file types is something that you cannot currently do, but something that we'll build towards in the future.
