### ISSUE TITLE
Add a way to manually insert document equivalences into our DB

### ISSUE THREAD

**Issue by csillag** [hypothesis/vision#7]
Moving discussion from https://github.com/hypothesis/h/issues/765.

---

Users should have a way to notify our server that a given set of URLs are equivalent.
Currently, we only detect document equivalence based on various metadata, but there are cases when this does not work.

Adding a simple way for the users to manually add the missing data would help.
Something like this:
- User finds an article somewhere on the 'net, and recognizes that it's simply a new copy of an article, available at somewhere else, too.
- User deploys H on the page
- With a few clicks, user activates the relevant function (probably using the settings panel (#551), or a link in the user menu), and enters an URL for an other copy of the document.
- The system stores the connection
- From now on, annotations made on either copy shows up on both pages.
- To uses currently watching one of the involved documents, we should announce the new synonym URLs. (That would require a new message type, but since now we have message types on all streams, that is not a problem.) Then the clients can load the new annotations.

Questions to work out:
- I am not sure about the data model we are currently using for storing equivalences. Does it support joining together two, previously independent group of equivalent documents?
- We should have a way to correct mistakenly entered equivalences. This should be taken into account when designing the implementation for this.

@tilgovi [commented](https://github.com/hypothesis/h/issues/765#issuecomment-24753327):

> The "logical documents" are not separate DB objects. Each URI is distinct,
> but has a set of aliases. When searching, we look up aliases for the searched URI
> and then search those, too. I think to "join two, previously independent group" would
> mean recursively resolving aliases on the server. Not terribly difficult, but expensive
> in terms of DB round trips. Though the common case would obviously be short
> (1 round trip discovers no new aliases, so ends).

About joining: maybe we could optimize the expensive lookup operations by applying some [Disjoint-set data structure](http://en.wikipedia.org/wiki/Disjoint-set_data_structure)s. That should decrease the number of required rounds.

@tilgovi:

> I'm wary of giving this power to users at all. Publishers are bad enough at doing
> this properly. Would users even understand what they're doing? Would they abuse
> it? It could be used to, say, put a bunch of annotations from an unrelated
> article onto a popular article. Are we then stuck having to implement moderation
> for document equivalence assertions?

 My thoughts about this:
- We don't have to just blindly accept all asserted equivalences!
- We can verify the content of the documents ourselves, and only allow the joining if the contents are indeed identical. (Or the difference is within a certain limit.)
- About spamming / attention grabbing: there are many other ways to do that, and currently, we don't have protection against any of them. I don't see why should this be a special case...

@tilgovi:

> I think this is a giant rabbit hole. A :dragon:. We should leave it alone. It might eat us.

My main point: one of the aspects of the current culture of debate (or lack thereof) what I hate the most is the fragmentation issue. I have bragged about this a lot, I won't repeat it here. I truly, madly, deeply despise fragmentation. (As in, artificial constraints, either in time, or in space, or in cyberspace, limiting the flow of useful information between areas that should be transparent otherwise.) Since this (having different copies of the same article online) is an aspect of fragmentation, I want to kill it. If it's a snake, then trample on it's head. Or kill it with fire :) Whatever. I want to see this (and many other similar issues) solved. 

---

For further discussion, see also [this thread](http://list.hypothes.is/archive/dev/2013-09/0000027.html) on the mailing list.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/827
