### ISSUE TITLE
Metrics / Statistics

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#75]
When running a service, it's useful to know some key metrics that characterize the major dimensions of activity.  

--------------------

These are an initial set of simple metrics.  These should be gathered and reported daily via an email to team@hypothes.is.

Acceptance criteria for the initial set:
- [ ] Total accounts
- [ ] New accounts
- [ ] Total activated accounts
- [ ] New activated accounts
- [ ] Total annotations
- [ ] New annotations
- [ ] Total contributors (accounts w/ > 1 annotation)
- [ ] Top 10 URIs annotated each day (in terms of total annotations + replies / URI)
- [ ] Top 10 annotators each day
- [ ] Either an email or a web link generated each day with these numbers reported

Please include any additional metrics from the list below that are easy to gather— or we can backlog these:
- Active users / day  (Uniques who have touched our app in the last month / day)
- Contributing users (Uniques who have made an annotation) / day
- Contributing / actives / day
- Total URIs annotated
- URIs annotated (publicly / privately) / day
- Avg Annotations / URI
- Activated accounts / total accounts [per day]
- Avg Replies / Page-level annotation
- Top ten tags / day  (trending tags)
- Avg length of an annotation in chars
- Public annotations / total annotations / day

This evolved from an earlier request, preserved below:

"Recently, U Mich requested / asked for access to the following info as a partner:
- who has annotated? how many times?
- when are annotations made?
- what type of content is being annotated?
- number of annotations
- what is most commented/annotated article?
- would a separate dashboard/interface be required to display this data?"

**Comment by BigBlueHat** [comment]
From the original list, but grouped by data source.

#### SQL
 - Total accounts
 - New accounts
 - Total activated accounts
 - New activated accounts

**NOTE:** It's not clear if we're collecting (or storing) enough data related to activation long enough to generate some of these numbers.

##### ElasticSearch
 - Total annotations
 - New annotations
 - Total contributors (accounts w/ > 1 annotation)
 - Top 10 URIs annotated each day (in terms of total annotations + replies / URI)
 - Top 10 annotators each day

**Comment by nickstenning** [comment]
Closing this in favour of split out cards.

**Comment by dwhly** [comment]
This is now referenced under #151
