### ISSUE TITLE
Archive a document with its annotations

### ISSUE THREAD

**Issue by dwhly** [hypothesis/vision#77]
Vision issue version of https://github.com/hypothesis/h/issues/810

From the original:

@caseyboyle has inquired as to whether we can archive a page with its annotations.

Perhaps an option from within H. to:
"Save document with annotations"

This would download the page as html, plus our interface and a local store of annotations.

You could click on the saved html file locally and view the annotations without any need for an internet connection. This package could also be hosted somewhere for others to access. The interface would need to make clear that it was an archived copy.

**Comment by BigBlueHat** [comment]
This sounds like a job for!!! https://github.com/hypothesis/via

Imagine a locally installed version of `via` that would auto-archive (locally) any thing you annotated via the proxy, and give you a UI for browsing those archive files.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/21
