### ISSUE TITLE
Direct Linking

### ISSUE THREAD

**Issue by JakeHartnell** [hypothesis/vision#87]
Linking directly to annotation as an overlay on the original source, not via an interstitial page.

---------------------
 
Originally posted in https://github.com/hypothesis/h/issues/769

Overview document is here: https://docs.google.com/a/hypothes.is/document/d/1x9e7jX3Xor6kMpU0cqD0wV8Om8Mxa2VEvH3zGBPLx3c/edit

**Use Case:** A user wants to tweet a link to an annotation they've made.  They want followers to be able to click and see the annotation in the context of the original page, regardless of whether they have the extension installed or not.

**Comment by jean** [comment]
Existing UI to address:

- The `<i class="h-icon-link btn-icon"></i>Link` on the annotation.
- The `<i class="h-icon-share"></i>` at the top of the annotations column, when annotation(s) is/are selected.

**Comment by robertknight** [comment]
We have implemented a first version of direct linking. At the bottom of annotation cards is a new 'Share' button which displays an `https://hyp.is` link which will take you to either the original URL or a Via-proxied version of the URL, open the sidebar and scroll to that annotation.

**Comment by JakeHartnell** [comment]
Awesome! :tada:
