### ISSUE TITLE
transcending the language barrier 1: transparent annotation of translated documents

### ISSUE THREAD

**Issue by csillag** [hypothesis/vision#9]
Moving discussion from https://github.com/hypothesis/h/issues/774

---

It's probably too early to do this, but let's enter this to the tracker anyway.

It should be possible to link translations back to their source documents.
This could be done either manually, as in #7, or automatically, as in #8.

We should also be able to automatically create a 1:1 mapping between the statements inside those documents. (Obviously, this only works with relatively tight, verbatim translations.)

And eventually, we should be able to attach annotations transparently, so that annotations added to one translation of the document appear on all other translations, too. (Obviously, we can't (yet) find out the exact cut-off positions inside the sentences, but we could at least attach them to the appropriate sentences.)

**Comment by ajpeddakotla** [comment]
closing in favor of https://github.com/hypothesis/product-backlog/issues/905
